// flow-typed signature: 36de5a2dc2ca07d43f429998f71add62
// flow-typed version: <<STUB>>/faucet_v0.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'faucet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'faucet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'faucet/bin/cmd' {
  declare module.exports: any;
}

declare module 'faucet/example/tape' {
  declare module.exports: any;
}

declare module 'faucet/example/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'faucet/bin/cmd.js' {
  declare module.exports: $Exports<'faucet/bin/cmd'>;
}
declare module 'faucet/example/tape.js' {
  declare module.exports: $Exports<'faucet/example/tape'>;
}
declare module 'faucet/example/test.js' {
  declare module.exports: $Exports<'faucet/example/test'>;
}
declare module 'faucet/index' {
  declare module.exports: $Exports<'faucet'>;
}
declare module 'faucet/index.js' {
  declare module.exports: $Exports<'faucet'>;
}
