// flow-typed signature: a3ab4db297fa4a90b90f9baf8c61cafd
// flow-typed version: <<STUB>>/lodash.isplainobject_v^4.0.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isplainobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isplainobject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isplainobject/index' {
  declare module.exports: $Exports<'lodash.isplainobject'>;
}
declare module 'lodash.isplainobject/index.js' {
  declare module.exports: $Exports<'lodash.isplainobject'>;
}
